version: '3.8'

services:
  api:
    build: .
    container_name: "workout_api"
    volumes:
      - ./app:/code/app
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=sqlite:///./workout.db
